"""init_db

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-08-03 23:00:00.000000

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("nonebot_plugin_llm_qa_system",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_qa_knowledge",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"bind_key": "nonebot_plugin_llm_qa_system"},
    )
    op.create_table(
        "llm_qa_answer_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("sources_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key", name=op.f("uq_llm_qa_answer_cache_cache_key")),
        info={"bind_key": "nonebot_plugin_llm_qa_system"},
    )
    op.create_table(
        "llm_qa_embedding_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("embedding", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "text", "model_name", name=op.f("uq_embedding_text_model")
        ),
        info={"bind_key": "nonebot_plugin_llm_qa_system"},
    )
    op.create_table(
        "llm_qa_knowledge_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"bind_key": "nonebot_plugin_llm_qa_system"},
    )
    op.create_table(
        "llm_qa_semantic_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("query_embedding", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("knowledge_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"bind_key": "nonebot_plugin_llm_qa_system"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_qa_semantic_cache")
    op.drop_table("llm_qa_knowledge_version")
    op.drop_table("llm_qa_embedding_cache")
    op.drop_table("llm_qa_answer_cache")
    op.drop_table("llm_qa_knowledge")
    # ### end Alembic commands ###
